# Generated by Django 5.0.7 on 2024-12-22 17:05

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_country_alter_lead_email_alter_lead_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('ig', 'Instagram'), ('fb', 'Facebook'), ('website', 'Website')], max_length=50, null=True),
        ),
    ]
