# Generated by Django 5.1.1 on 2024-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='friday_active',
            field=models.BooleanField(default=False, verbose_name='Friday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='friday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='friday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='friday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Friday Work Type'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='monday_active',
            field=models.BooleanField(default=False, verbose_name='Monday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='monday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='monday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='monday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Monday Work Type'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='saturday_active',
            field=models.BooleanField(default=False, verbose_name='Saturday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='saturday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Saturday Work Type'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='sunday_active',
            field=models.BooleanField(default=False, verbose_name='Sunday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='sunday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='sunday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Sunday Work Type'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='thursday_active',
            field=models.BooleanField(default=False, verbose_name='Thursday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='thursday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Thursday Work Type'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='tuesday_active',
            field=models.BooleanField(default=False, verbose_name='Tuesday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='tuesday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Tuesday Work Type'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='wednesday_active',
            field=models.BooleanField(default=False, verbose_name='Wednesday Active'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday End Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday Start Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='wednesday_work_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True, verbose_name='Wednesday Work Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Job Number'),
        ),
    ]
