# Generated by Django 5.1.1 on 2024-09-06 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_workschedule_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='friday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='friday_work_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='monday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='monday_work_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='saturday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='saturday_work_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='sunday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='sunday_work_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='thursday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='thursday_work_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tuesday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tuesday_work_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='wednesday_active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='wednesday_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='wednesday_work_type',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=9)),
                ('active', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=6, null=True)),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employee.workschedule')),
            ],
        ),
    ]
