# Generated by Django 5.1.1 on 2024-09-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_workschedule_friday_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayschedule',
            unique_together={('work_schedule', 'day_of_week')},
        ),
    ]
