# Generated by Django 5.1.1 on 2024-09-06 10:51

import django.db.models.deletion
import employee.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_dayschedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=employee.models.employee_file_upload_path)),
                ('file_type', models.CharField(choices=[('cv', 'CV'), ('profile_picture', 'Profile Picture'), ('document', 'Document'), ('pdf', 'PDF')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Files',
            },
        ),
    ]
