# Generated by Django 5.1.1 on 2024-09-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefile',
            options={},
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='file_type',
            field=models.CharField(choices=[('cv', 'CV'), ('profile_picture', 'Profile Picture'), ('document', 'Document')], max_length=50),
        ),
    ]
