# Generated by Django 4.2.4 on 2024-07-20 15:08

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_appointment_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinformation',
            name='uploaded_files',
            field=models.FileField(blank=True, null=True, upload_to=apps.models.user_directory_path),
        ),
    ]
