# Generated by Django 4.2.4 on 2024-07-20 17:15

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_medicalinformation_uploaded_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='uploaded_files',
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, to='apps.uploadedfile'),
        ),
    ]
