# Generated by Django 4.2.4 on 2024-07-20 17:56

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_uploadedfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='uploaded_files',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='uploaded_files',
            field=models.FileField(blank=True, null=True, upload_to=apps.models.user_directory_path),
        ),
    ]
