# Generated by Django 4.2.4 on 2024-07-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_medicalinformation_uploaded_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
