# Generated by Django 4.2.4 on 2024-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_insurance_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
