# Generated by Django 4.2.4 on 2024-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_insurance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Intersex')], max_length=50, null=True),
        ),
    ]
