# Generated by Django 4.2.4 on 2024-07-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_user_referral_code_user_referred_by_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
