# Generated by Django 4.2.4 on 2024-07-21 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
