# Generated by Django 4.2.4 on 2024-07-21 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_referral_code_alter_referral_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
