# Generated by Django 4.2.4 on 2024-07-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_user_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beyondblog_profileid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
