# Generated by Django 5.0.7 on 2024-08-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_homepage_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('Implants', 'Implants'), ('Crowns', 'Crowns'), ('Dental Procedures', 'Dental Procedures'), ('Additional Services', 'Additional Services')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.treatmentplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.treatmentproduct')),
            ],
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='products',
            field=models.ManyToManyField(through='apps.TreatmentPlanItem', to='apps.treatmentproduct'),
        ),
    ]
