# Generated by Django 5.0.7 on 2024-08-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_treatmentproduct_treatmentplan_treatmentplanitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
