# Generated by Django 5.0.7 on 2024-08-29 06:00

import apps.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_treatmentplan_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='uploaded_files',
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='additional_info',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='family_history',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medical_conditions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.models.user_directory_path)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('medical_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='apps.medicalinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
