# Generated by Django 5.0.7 on 2024-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_remove_medicalinformation_uploaded_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentproduct',
            name='max_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5),
        ),
    ]
