# Generated by Django 5.0.7 on 2024-08-31 18:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_user_nationality_alter_emergencycontact_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
