# Generated by Django 5.1.1 on 2024-09-06 15:14

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_user_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'verbose_name': 'Emergency Contact', 'verbose_name_plural': 'Emergency Contacts'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='hospitalstay',
            options={'verbose_name': 'Hospital Stay', 'verbose_name_plural': 'Hospital Stays'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Insurance', 'verbose_name_plural': 'Insurances'},
        ),
        migrations.AlterModelOptions(
            name='medicalinformation',
            options={'verbose_name': 'Medical Information', 'verbose_name_plural': 'Medical Information Records'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='messagegroup',
            options={'verbose_name': 'Message Group', 'verbose_name_plural': 'Message Groups'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='treatmentplan',
            options={'verbose_name': 'Treatment Plan', 'verbose_name_plural': 'Treatment Plans'},
        ),
        migrations.AlterModelOptions(
            name='treatmentplanitem',
            options={'verbose_name': 'Treatment Plan Item', 'verbose_name_plural': 'Treatment Plan Items'},
        ),
        migrations.AlterModelOptions(
            name='treatmentproduct',
            options={'verbose_name': 'Treatment Product', 'verbose_name_plural': 'Treatment Products'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=wagtail.fields.RichTextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(max_length=30, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='zipcode',
            field=models.CharField(max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='admission',
            field=models.DateTimeField(verbose_name='Admission'),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='discharge',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discharge'),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.hospital', verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Insurance Company'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Policy Number'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='additional_info',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='family_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Family History'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.insurance', verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medical_conditions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medical Conditions'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medications',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medications'),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Intersex')], max_length=50, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apps.messagegroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_members',
            field=models.ManyToManyField(related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Read Members'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='active',
            field=models.BooleanField(verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='directions',
            field=models.CharField(max_length=1000, verbose_name='Directions'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=200, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed',
            field=models.DateTimeField(verbose_name='Prescribed'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='Referred'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referrer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='products',
            field=models.ManyToManyField(through='apps.TreatmentPlanItem', to='apps.treatmentproduct', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.treatmentproduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.treatmentplan', verbose_name='Treatment Plan'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='category',
            field=models.CharField(choices=[('Implants', 'Implants'), ('Crowns', 'Crowns'), ('Dental Procedures', 'Dental Procedures'), ('Additional Services', 'Additional Services')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='max_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Max Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='beyondblog_profileid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Blog Profile ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.emergencycontact', verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Logout Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.medicalinformation', verbose_name='Medical Information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referred By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thread ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
