# Generated by Django 5.0.7 on 2024-11-13 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('arrival_hour', models.TimeField(verbose_name='Arrival Hour')),
                ('arrival_flight_number', models.CharField(max_length=50, verbose_name='Arrival Flight Number')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('departure_hour', models.TimeField(verbose_name='Departure Hour')),
                ('departure_flight_number', models.CharField(max_length=50, verbose_name='Departure Flight Number')),
            ],
            options={
                'verbose_name': 'Flight Reservation',
                'verbose_name_plural': 'Flight Reservations',
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.treatmentplan', verbose_name='Treatment Plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
            },
        ),
        migrations.CreateModel(
            name='PatientSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.accommodation', verbose_name='Accommodation')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.appointment', verbose_name='Appointment')),
                ('flight_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.flightreservation', verbose_name='Flight Reservation')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.hospital', verbose_name='Hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient Schedule',
                'verbose_name_plural': 'Patient Schedules',
            },
        ),
    ]
