# Generated by Django 5.0.7 on 2024-11-14 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_flightreservation_accommodation_patientschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reservations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
