# Generated by Django 5.0.7 on 2024-11-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_flightreservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Family', 'Family')], max_length=50, verbose_name='Room Type')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Night')),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities', verbose_name='Amenities')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='name',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='duration_of_stay',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration of Stay (in nights)'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.hotel', verbose_name='Hotel'),
        ),
    ]
