# Generated by Django 5.0.7 on 2024-11-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_hotel_remove_accommodation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='final_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Final Discount Percentage'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount Percentage'),
        ),
    ]
