# Generated by Django 5.0.7 on 2024-11-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_remove_treatmentplan_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Amount'),
        ),
    ]
