# Generated by Django 5.0.7 on 2025-07-25 15:18

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_auto_20241114_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentproduct',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, help_text='Country where this product is manufactured or originates from', max_length=2, null=True, verbose_name='Country of Origin'),
        ),
    ]
