# Generated by Django 5.0.7 on 2025-07-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_treatmentproduct_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoiceninja_client_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Invoice Ninja Client ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoiceninja_last_sync_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync Attempt'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoiceninja_sync_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Sync Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoiceninja_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('retry', 'Retry Required')], default='pending', max_length=20, verbose_name='Invoice Ninja Sync Status'),
        ),
    ]
