# Generated by Django 5.0.7 on 2025-07-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_user_invoiceninja_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentproduct',
            name='invoiceninja_last_sync_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync Attempt'),
        ),
        migrations.AddField(
            model_name='treatmentproduct',
            name='invoiceninja_product_id',
            field=models.CharField(blank=True, help_text='ID of this product in Invoice Ninja', max_length=50, null=True, verbose_name='Invoice Ninja Product ID'),
        ),
        migrations.AddField(
            model_name='treatmentproduct',
            name='invoiceninja_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', help_text='Sync status with Invoice Ninja', max_length=20, verbose_name='Invoice Ninja Sync Status'),
        ),
    ]
