# Generated by Django 5.0.7 on 2025-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_treatmentplan_invoiceninja_last_sync_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='invoiceninja_quote_portal_url',
            field=models.URLField(blank=True, help_text='Patient portal URL for viewing/approving this quote', null=True, verbose_name='Invoice Ninja Portal URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoiceninja_client_portal_url',
            field=models.URLField(blank=True, help_text='Client portal URL for accessing Invoice Ninja dashboard', null=True, verbose_name='Invoice Ninja Client Portal URL'),
        ),
    ]
