# Generated by Django 5.0.7 on 2025-07-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_treatmentplan_invoiceninja_quote_portal_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='invoiceninja_quote_portal_url',
        ),
    ]
