# Generated by Django 5.0.7 on 2025-07-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_remove_treatmentplan_invoiceninja_quote_portal_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invoiceninja_client_portal_url',
        ),
    ]
